<%
  encoding = 'unicode'
  if ENV['OSEM_DB_ADAPTER'] == 'mysql2'
    encoding = 'utf8'
  end
%>


default: &default
  adapter: <%= ENV['OSEM_DB_ADAPTER'] || 'postgresql' %>
  encoding: <%= encoding %>
  host: <%= ENV['OSEM_DB_HOST'] || 'database' %>
  port: <%= ENV['OSEM_DB_PORT'] || '5432' %>
  username: <%= ENV['OSEM_DB_USER'] || 'postgres' %>
  password: <%= ENV['OSEM_DB_PASSWORD'] || 'mysecretpassword' %>
  database: <%= ENV['OSEM_DB_NAME'] || 'postgres' %>
  pool: 30
  timeout: 70000

development:
  <<: *default
  host: localhost
  database: osem_development

# Warning: The database defined as "test" will be erased and
# re-generated when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  adapter: <%= ENV['OSEM_DB_ADAPTER']='sqlite3' %>
  host: localhost
  database: osem_test

production:
  <<: *default